version: '3'

services:
  kie-server:
    build: docker/kie-server
    depends_on: 
    - drools-wb
    expose:
    - 8080/tcp
  drools-wb:
    build: docker/drools-wb
    extra_hosts:
      host.docker.internal: host-gateway
    expose:
    - 8080/tcp
  proxy:
    build: docker/proxy
    restart: always
    depends_on: 
    - kie-server
    - drools-wb
    ports:
    - 80:80